source 'https://rubygems.org'


gem 'rails', '4.1.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'sqlite3'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

group :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'factory'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers', require: false
end

gem 'debugger', :group => :development
gem 'redis'
gem 'devise'
